// Centralized mock data for the RR GROUP storefront.
// Isolated here so a real API/back end can replace it later without touching UI.

import type { Category, Order, Product } from "./types"

export const categories: Category[] = [
  {
    slug: "software-licenses",
    name: "Software Licenses",
    description:
      "Production-ready ERP, CRM and analytics platforms with annual licensing and priority support.",
    image: "/products/rr-erp.png",
    productCount: 3,
  },
  {
    slug: "website-templates",
    name: "Website Templates",
    description: "Premium, conversion-focused website and dashboard templates for modern teams.",
    image: "/products/analytics-template.png",
    productCount: 2,
  },
  {
    slug: "business-hardware",
    name: "Business Hardware",
    description: "Point-of-sale terminals, scanners and IoT devices engineered for reliability.",
    image: "/products/smartpos.png",
    productCount: 3,
  },
  {
    slug: "cloud-services",
    name: "Cloud Services",
    description: "Managed cloud backup, hosting and infrastructure plans that scale with you.",
    image: "/products/cloud-backup.png",
    productCount: 1,
  },
  {
    slug: "marketing-tools",
    name: "Marketing Tools",
    description: "Email automation and SEO toolkits to grow reach and drive qualified leads.",
    image: "/products/email-suite.png",
    productCount: 2,
  },
  {
    slug: "accessories",
    name: "Accessories",
    description: "Workspace essentials and connectivity gear for productive teams.",
    image: "/products/usb-hub.png",
    productCount: 2,
  },
]

const genericSpecs = [
  { label: "License", value: "12 months, renewable" },
  { label: "Support", value: "Priority email & chat" },
  { label: "Updates", value: "Included for license term" },
  { label: "Deployment", value: "Cloud or on-premise" },
]

const genericReviews = (name: string) => [
  {
    id: "r1",
    author: "Ananya Mehta",
    avatarInitials: "AM",
    rating: 5,
    date: "Aug 12, 2026",
    title: "Exactly what our team needed",
    body: `We rolled ${name} out across three departments in a week. Setup was smooth and the support team was responsive.`,
    verified: true,
  },
  {
    id: "r2",
    author: "Rahul Kapoor",
    avatarInitials: "RK",
    rating: 4,
    date: "Jul 29, 2026",
    title: "Great value for the price",
    body: "Solid performance and a clean interface. Would love a few more integrations, but overall very happy.",
    verified: true,
  },
  {
    id: "r3",
    author: "Priya Nair",
    avatarInitials: "PN",
    rating: 5,
    date: "Jul 03, 2026",
    title: "Reliable and well documented",
    body: "Documentation is thorough and the onboarding call helped us get to value quickly.",
    verified: false,
  },
]

export const products: Product[] = [
  {
    id: "p1",
    slug: "rr-commerce-erp-pro",
    name: "RR Commerce ERP Pro",
    category: "Software Licenses",
    categorySlug: "software-licenses",
    brand: "RR GROUP",
    sku: "RR-ERP-PRO-01",
    shortDescription: "End-to-end ERP for inventory, finance and operations.",
    description:
      "RR Commerce ERP Pro unifies inventory, procurement, finance and sales into a single operational platform. Automate purchase orders, track stock across warehouses in real time, and generate finance-ready reports without spreadsheets.",
    images: ["/products/rr-erp.png"],
    price: 48999,
    originalPrice: 64999,
    rating: 4.8,
    reviewCount: 214,
    stock: 40,
    stockStatus: "in-stock",
    badge: "bestseller",
    variants: [
      {
        name: "Plan",
        options: [
          { id: "v1", label: "Standard (10 users)", value: "standard", available: true },
          { id: "v2", label: "Business (50 users)", value: "business", available: true },
          { id: "v3", label: "Enterprise (unlimited)", value: "enterprise", available: true },
        ],
      },
    ],
    specs: [
      { label: "Modules", value: "Inventory, Finance, Sales, HR" },
      ...genericSpecs,
    ],
    reviews: genericReviews("RR Commerce ERP Pro"),
    tags: ["erp", "operations", "finance", "inventory"],
    createdAt: "2026-05-10",
    popularity: 98,
  },
  {
    id: "p2",
    slug: "rr-crm-suite-enterprise",
    name: "RR CRM Suite Enterprise",
    category: "Software Licenses",
    categorySlug: "software-licenses",
    brand: "RR GROUP",
    sku: "RR-CRM-ENT-02",
    shortDescription: "Pipeline, contacts and automation for revenue teams.",
    description:
      "Manage the full customer lifecycle with a visual sales pipeline, automated follow-ups, and deep reporting. RR CRM Suite Enterprise keeps marketing, sales and support aligned around a single source of truth.",
    images: ["/products/rr-crm.png"],
    price: 39999,
    originalPrice: 49999,
    rating: 4.7,
    reviewCount: 168,
    stock: 55,
    stockStatus: "in-stock",
    badge: "bestseller",
    variants: [
      {
        name: "Plan",
        options: [
          { id: "v1", label: "Growth", value: "growth", available: true },
          { id: "v2", label: "Scale", value: "scale", available: true },
          { id: "v3", label: "Enterprise", value: "enterprise", available: true },
        ],
      },
    ],
    specs: [{ label: "Seats", value: "From 10 users" }, ...genericSpecs],
    reviews: genericReviews("RR CRM Suite Enterprise"),
    tags: ["crm", "sales", "pipeline", "automation"],
    createdAt: "2026-04-22",
    popularity: 95,
  },
  {
    id: "p3",
    slug: "rr-analytics-cloud",
    name: "RR Analytics Cloud",
    category: "Software Licenses",
    categorySlug: "software-licenses",
    brand: "RR GROUP",
    sku: "RR-ANL-CLD-03",
    shortDescription: "Real-time BI dashboards and reporting.",
    description:
      "Connect your data sources and build live dashboards in minutes. RR Analytics Cloud delivers real-time KPIs, scheduled reports and role-based sharing for data-driven teams.",
    images: ["/products/analytics-template.png"],
    price: 24999,
    originalPrice: 29999,
    rating: 4.6,
    reviewCount: 121,
    stock: 8,
    stockStatus: "low-stock",
    badge: "sale",
    specs: [{ label: "Data sources", value: "40+ connectors" }, ...genericSpecs],
    reviews: genericReviews("RR Analytics Cloud"),
    tags: ["analytics", "bi", "dashboards", "reporting"],
    createdAt: "2026-06-01",
    popularity: 88,
  },
  {
    id: "p4",
    slug: "corporate-website-kit",
    name: "Corporate Website Kit",
    category: "Website Templates",
    categorySlug: "website-templates",
    brand: "RR Studio",
    sku: "RR-TPL-CORP-04",
    shortDescription: "Multi-page corporate site template with CMS.",
    description:
      "A polished, fully responsive corporate website template with 12 pre-built pages, blog layouts and a headless-CMS-ready structure. Ship a premium brand presence in days.",
    images: ["/products/website-kit.png"],
    price: 5999,
    originalPrice: 8999,
    rating: 4.9,
    reviewCount: 342,
    stock: 200,
    stockStatus: "in-stock",
    badge: "bestseller",
    specs: [
      { label: "Pages", value: "12 templates" },
      { label: "Framework", value: "Next.js + Tailwind" },
      { label: "License", value: "Single project" },
      { label: "Updates", value: "Lifetime" },
    ],
    reviews: genericReviews("Corporate Website Kit"),
    tags: ["template", "website", "nextjs", "corporate"],
    createdAt: "2026-06-18",
    popularity: 92,
  },
  {
    id: "p5",
    slug: "analytics-dashboard-template",
    name: "Analytics Dashboard Template",
    category: "Website Templates",
    categorySlug: "website-templates",
    brand: "RR Studio",
    sku: "RR-TPL-DASH-05",
    shortDescription: "Admin dashboard UI kit with 30+ screens.",
    description:
      "A comprehensive admin dashboard template featuring 30+ screens, charts, data tables and dark mode. Perfect starting point for internal tools and SaaS products.",
    images: ["/products/analytics-template.png"],
    price: 4499,
    originalPrice: 6499,
    rating: 4.7,
    reviewCount: 189,
    stock: 150,
    stockStatus: "in-stock",
    badge: "new",
    specs: [
      { label: "Screens", value: "30+" },
      { label: "Framework", value: "React + Tailwind" },
      { label: "License", value: "Single project" },
      { label: "Updates", value: "Lifetime" },
    ],
    reviews: genericReviews("Analytics Dashboard Template"),
    tags: ["template", "dashboard", "admin", "react"],
    createdAt: "2026-08-02",
    popularity: 84,
  },
  {
    id: "p6",
    slug: "smartpos-terminal-x1",
    name: "SmartPOS Terminal X1",
    category: "Business Hardware",
    categorySlug: "business-hardware",
    brand: "RR Devices",
    sku: "RR-HW-POS-06",
    shortDescription: "All-in-one touchscreen POS with printer.",
    description:
      "A sleek all-in-one point-of-sale terminal with a 15-inch touchscreen, built-in thermal printer and dual-band Wi-Fi. Pre-configured to work with RR Commerce ERP out of the box.",
    images: ["/products/smartpos.png"],
    price: 34999,
    originalPrice: 42999,
    rating: 4.5,
    reviewCount: 76,
    stock: 12,
    stockStatus: "low-stock",
    badge: "sale",
    variants: [
      {
        name: "Color",
        options: [
          { id: "v1", label: "Graphite", value: "graphite", available: true },
          { id: "v2", label: "Silver", value: "silver", available: true },
        ],
      },
    ],
    specs: [
      { label: "Display", value: "15\" capacitive touch" },
      { label: "Printer", value: "Built-in 80mm thermal" },
      { label: "Connectivity", value: "Wi-Fi, Ethernet, Bluetooth" },
      { label: "Warranty", value: "2 years" },
    ],
    reviews: genericReviews("SmartPOS Terminal X1"),
    tags: ["pos", "hardware", "retail", "terminal"],
    createdAt: "2026-03-15",
    popularity: 79,
  },
  {
    id: "p7",
    slug: "barcode-scanner-pro",
    name: "Barcode Scanner Pro",
    category: "Business Hardware",
    categorySlug: "business-hardware",
    brand: "RR Devices",
    sku: "RR-HW-SCN-07",
    shortDescription: "Wireless 2D barcode & QR scanner.",
    description:
      "A rugged wireless 2D scanner reading barcodes and QR codes at up to 300 scans per second. Charging cradle and 12-hour battery included for all-day warehouse use.",
    images: ["/products/barcode-scanner.png"],
    price: 7499,
    originalPrice: 9499,
    rating: 4.4,
    reviewCount: 58,
    stock: 0,
    stockStatus: "out-of-stock",
    specs: [
      { label: "Type", value: "2D wireless" },
      { label: "Range", value: "Up to 30m" },
      { label: "Battery", value: "12 hours" },
      { label: "Warranty", value: "1 year" },
    ],
    reviews: genericReviews("Barcode Scanner Pro"),
    tags: ["scanner", "hardware", "warehouse"],
    createdAt: "2026-02-20",
    popularity: 61,
  },
  {
    id: "p8",
    slug: "iot-sensor-kit",
    name: "IoT Sensor Starter Kit",
    category: "Business Hardware",
    categorySlug: "business-hardware",
    brand: "RR Devices",
    sku: "RR-HW-IOT-08",
    shortDescription: "Environmental sensor kit with gateway.",
    description:
      "Monitor temperature, humidity and motion across facilities with this plug-and-play IoT kit. Includes a gateway, six wireless sensors and a cloud dashboard trial.",
    images: ["/products/iot-kit.png"],
    price: 12999,
    originalPrice: 15999,
    rating: 4.3,
    reviewCount: 34,
    stock: 25,
    stockStatus: "in-stock",
    badge: "new",
    specs: [
      { label: "Sensors", value: "6 included" },
      { label: "Protocol", value: "Zigbee + Wi-Fi" },
      { label: "Range", value: "Up to 100m" },
      { label: "Warranty", value: "1 year" },
    ],
    reviews: genericReviews("IoT Sensor Starter Kit"),
    tags: ["iot", "sensors", "hardware", "monitoring"],
    createdAt: "2026-07-28",
    popularity: 66,
  },
  {
    id: "p9",
    slug: "cloud-backup-1tb",
    name: "Cloud Backup 1TB Plan",
    category: "Cloud Services",
    categorySlug: "cloud-services",
    brand: "RR Cloud",
    sku: "RR-CLD-BK-09",
    shortDescription: "Encrypted managed backup, 1TB annual.",
    description:
      "Automated, encrypted backups for your critical business data with 1TB of storage, versioning and one-click restore. Managed entirely by RR Cloud with 99.9% uptime.",
    images: ["/products/cloud-backup.png"],
    price: 8999,
    originalPrice: 11999,
    rating: 4.6,
    reviewCount: 97,
    stock: 999,
    stockStatus: "in-stock",
    variants: [
      {
        name: "Term",
        options: [
          { id: "v1", label: "Annual", value: "annual", available: true },
          { id: "v2", label: "Monthly", value: "monthly", available: true },
        ],
      },
    ],
    specs: [
      { label: "Storage", value: "1TB" },
      { label: "Encryption", value: "AES-256" },
      { label: "Uptime", value: "99.9% SLA" },
      { label: "Support", value: "24/7" },
    ],
    reviews: genericReviews("Cloud Backup 1TB Plan"),
    tags: ["cloud", "backup", "storage", "managed"],
    createdAt: "2026-05-30",
    popularity: 74,
  },
  {
    id: "p10",
    slug: "email-marketing-suite",
    name: "Email Marketing Suite",
    category: "Marketing Tools",
    categorySlug: "marketing-tools",
    brand: "RR Marketing",
    sku: "RR-MKT-EM-10",
    shortDescription: "Automation, campaigns and analytics.",
    description:
      "Design campaigns, build automated journeys and track engagement with a drag-and-drop email builder. Includes deliverability tools and detailed analytics.",
    images: ["/products/email-suite.png"],
    price: 6499,
    originalPrice: 8999,
    rating: 4.5,
    reviewCount: 143,
    stock: 500,
    stockStatus: "in-stock",
    badge: "bestseller",
    specs: [
      { label: "Contacts", value: "Up to 25,000" },
      { label: "Automation", value: "Unlimited journeys" },
      { label: "Templates", value: "80+ included" },
      { label: "Support", value: "Priority chat" },
    ],
    reviews: genericReviews("Email Marketing Suite"),
    tags: ["marketing", "email", "automation", "campaigns"],
    createdAt: "2026-04-05",
    popularity: 81,
  },
  {
    id: "p11",
    slug: "seo-optimizer-toolkit",
    name: "SEO Optimizer Toolkit",
    category: "Marketing Tools",
    categorySlug: "marketing-tools",
    brand: "RR Marketing",
    sku: "RR-MKT-SEO-11",
    shortDescription: "Keyword, audit and rank-tracking suite.",
    description:
      "Improve organic visibility with keyword research, technical site audits, backlink analysis and daily rank tracking — all in one toolkit with actionable recommendations.",
    images: ["/products/seo-toolkit.png"],
    price: 5499,
    originalPrice: 7499,
    rating: 4.4,
    reviewCount: 88,
    stock: 6,
    stockStatus: "low-stock",
    badge: "sale",
    specs: [
      { label: "Keywords tracked", value: "Up to 2,000" },
      { label: "Site audits", value: "Unlimited" },
      { label: "Reports", value: "White-label" },
      { label: "Support", value: "Email" },
    ],
    reviews: genericReviews("SEO Optimizer Toolkit"),
    tags: ["marketing", "seo", "keywords", "audit"],
    createdAt: "2026-06-25",
    popularity: 70,
  },
  {
    id: "p12",
    slug: "usb-c-hub-station",
    name: "USB-C Hub Station 11-in-1",
    category: "Accessories",
    categorySlug: "accessories",
    brand: "RR Devices",
    sku: "RR-ACC-HUB-12",
    shortDescription: "11-port docking station with 4K HDMI.",
    description:
      "Expand any laptop with 11 ports including dual 4K HDMI, Gigabit Ethernet, SD card readers and 100W passthrough charging. Aluminum body stays cool under load.",
    images: ["/products/usb-hub.png"],
    price: 4299,
    originalPrice: 5999,
    rating: 4.6,
    reviewCount: 254,
    stock: 80,
    stockStatus: "in-stock",
    variants: [
      {
        name: "Color",
        options: [
          { id: "v1", label: "Space Gray", value: "gray", available: true },
          { id: "v2", label: "Silver", value: "silver", available: false },
        ],
      },
    ],
    specs: [
      { label: "Ports", value: "11 total" },
      { label: "Video", value: "Dual 4K HDMI" },
      { label: "Charging", value: "100W passthrough" },
      { label: "Warranty", value: "18 months" },
    ],
    reviews: genericReviews("USB-C Hub Station 11-in-1"),
    tags: ["accessory", "usb-c", "dock", "hub"],
    createdAt: "2026-07-10",
    popularity: 77,
  },
  {
    id: "p13",
    slug: "wireless-presenter",
    name: "Wireless Presenter Remote",
    category: "Accessories",
    categorySlug: "accessories",
    brand: "RR Devices",
    sku: "RR-ACC-PRS-13",
    shortDescription: "Laser presenter with 30m range.",
    description:
      "Present with confidence using this ergonomic wireless remote featuring a red laser pointer, intuitive slide controls and a 30-meter range. USB-C rechargeable.",
    images: ["/products/presenter.png"],
    price: 1999,
    originalPrice: 2799,
    rating: 4.3,
    reviewCount: 112,
    stock: 3,
    stockStatus: "low-stock",
    specs: [
      { label: "Range", value: "30m" },
      { label: "Battery", value: "USB-C, 20 hrs" },
      { label: "Compatibility", value: "Windows, macOS" },
      { label: "Warranty", value: "1 year" },
    ],
    reviews: genericReviews("Wireless Presenter Remote"),
    tags: ["accessory", "presenter", "remote"],
    createdAt: "2026-03-01",
    popularity: 58,
  },
]

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug)
}

export function getProductsByCategory(categorySlug: string): Product[] {
  return products.filter((p) => p.categorySlug === categorySlug)
}

export function getRelatedProducts(product: Product, limit = 4): Product[] {
  return products
    .filter((p) => p.id !== product.id && p.categorySlug === product.categorySlug)
    .concat(products.filter((p) => p.id !== product.id && p.categorySlug !== product.categorySlug))
    .slice(0, limit)
}

export const featuredProducts = products.filter((p) => p.badge === "bestseller")
export const newArrivals = products.filter((p) => p.badge === "new").concat(products.slice(0, 2))
export const bestSellers = [...products].sort((a, b) => b.popularity - a.popularity).slice(0, 4)

export const orders: Order[] = [
  {
    id: "RR-2026-10432",
    date: "Sep 14, 2026",
    status: "shipped",
    paymentStatus: "paid",
    paymentMethod: "UPI • rrgroup@okhdfc",
    items: [
      {
        name: "RR Commerce ERP Pro",
        image: "/products/rr-erp.png",
        variant: "Business (50 users)",
        price: 48999,
        quantity: 1,
      },
      {
        name: "USB-C Hub Station 11-in-1",
        image: "/products/usb-hub.png",
        variant: "Space Gray",
        price: 4299,
        quantity: 2,
      },
    ],
    subtotal: 57597,
    discount: 5000,
    shipping: 0,
    tax: 9467,
    total: 62064,
    shippingAddress: {
      name: "Vikram Sethi",
      line1: "402, Orchid Towers, Bandra West",
      city: "Mumbai",
      state: "Maharashtra",
      postalCode: "400050",
      country: "India",
      phone: "+91 98200 12345",
    },
    timeline: [
      { status: "placed", label: "Order Placed", date: "Sep 14, 10:24 AM", done: true },
      { status: "confirmed", label: "Confirmed", date: "Sep 14, 10:31 AM", done: true },
      { status: "processing", label: "Processing", date: "Sep 15, 09:10 AM", done: true },
      { status: "shipped", label: "Shipped", date: "Sep 16, 02:45 PM", done: true },
      { status: "out-for-delivery", label: "Out for Delivery", date: "Expected Sep 19", done: false },
      { status: "delivered", label: "Delivered", date: "Expected Sep 19", done: false },
    ],
  },
  {
    id: "RR-2026-10318",
    date: "Sep 02, 2026",
    status: "delivered",
    paymentStatus: "paid",
    paymentMethod: "Card • Visa •••• 4821",
    items: [
      {
        name: "Corporate Website Kit",
        image: "/products/website-kit.png",
        price: 5999,
        quantity: 1,
      },
    ],
    subtotal: 5999,
    discount: 0,
    shipping: 0,
    tax: 1080,
    total: 7079,
    shippingAddress: {
      name: "Vikram Sethi",
      line1: "402, Orchid Towers, Bandra West",
      city: "Mumbai",
      state: "Maharashtra",
      postalCode: "400050",
      country: "India",
      phone: "+91 98200 12345",
    },
    timeline: [
      { status: "placed", label: "Order Placed", date: "Sep 02, 04:12 PM", done: true },
      { status: "confirmed", label: "Confirmed", date: "Sep 02, 04:15 PM", done: true },
      { status: "processing", label: "Processing", date: "Sep 02, 04:20 PM", done: true },
      { status: "shipped", label: "Shipped", date: "Sep 02, 05:00 PM", done: true },
      { status: "out-for-delivery", label: "Out for Delivery", date: "Sep 03, 09:30 AM", done: true },
      { status: "delivered", label: "Delivered", date: "Sep 03, 01:15 PM", done: true },
    ],
  },
  {
    id: "RR-2026-10190",
    date: "Aug 21, 2026",
    status: "processing",
    paymentStatus: "pending",
    paymentMethod: "Net Banking • HDFC",
    items: [
      {
        name: "SmartPOS Terminal X1",
        image: "/products/smartpos.png",
        variant: "Graphite",
        price: 34999,
        quantity: 1,
      },
      {
        name: "Barcode Scanner Pro",
        image: "/products/barcode-scanner.png",
        price: 7499,
        quantity: 1,
      },
    ],
    subtotal: 42498,
    discount: 2000,
    shipping: 199,
    tax: 7290,
    total: 47987,
    shippingAddress: {
      name: "Vikram Sethi",
      line1: "12, Residency Road",
      city: "Bengaluru",
      state: "Karnataka",
      postalCode: "560025",
      country: "India",
      phone: "+91 98200 12345",
    },
    timeline: [
      { status: "placed", label: "Order Placed", date: "Aug 21, 11:02 AM", done: true },
      { status: "confirmed", label: "Confirmed", date: "Aug 21, 11:20 AM", done: true },
      { status: "processing", label: "Processing", date: "Aug 22, 10:00 AM", done: true },
      { status: "shipped", label: "Shipped", date: "Pending", done: false },
      { status: "out-for-delivery", label: "Out for Delivery", date: "Pending", done: false },
      { status: "delivered", label: "Delivered", date: "Pending", done: false },
    ],
  },
]

export function getOrderById(id: string): Order | undefined {
  return orders.find((o) => o.id === id)
}

export const recentSearches = ["ERP software", "website template", "POS terminal", "cloud backup"]
export const trendingSearches = ["CRM", "SEO toolkit", "USB-C hub", "email marketing", "IoT kit"]
